FROM rocker/verse:3.6.3
LABEL MAINTAINER="github.com/ftwkoopmans/msdap"

# libpoppler is a pdftools requirement
# libnetcdf is required downstream by R package ncdf4, which is an upstream dependency
RUN apt-get update && apt-get install -y --no-install-recommends \
  libnetcdf-dev \
  netcdf-bin \
  libpoppler-cpp-dev

# install missing tinytex packages
RUN /opt/TinyTeX/bin/*/tlmgr install ifxetex ifluatex oberdiek graphics graphics-cfg graphics-def


# explicitly use BiocManager for Bioconductor dependencies (more robust than relying on devtools to install our Bioconductor dependencies, especially for ProtGenerics and MSnbase)
RUN R -e "BiocManager::install(c('ProtGenerics', 'MSnbase', 'limma', 'vsn', 'pcaMethods', 'DEqMS'), update=F, ask=F)"

# specify r-project cloud server as repository and install/update selected packages (in this docker image, it'll otherwise default to mran.microsoft and for example use outdated version 1.3 of the iq package)
# further, we need an updated version of tidyverse packages (e.g. dplyr verion 1.0 or later for newly introduced function dplyr::across() )
RUN R -e "install.packages(c('devtools', 'tidyverse', 'iq'), repos = 'https://cloud.r-project.org')"

# install msdap R package from github
RUN R -e "devtools::install_github('ftwkoopmans/msdap@0.2.8.1', upgrade = 'never')"

# make sure the rstudio user can install and upgrade packages
RUN chown -R rstudio:rstudio /usr/local/lib/R/library
RUN chown -R rstudio:rstudio /usr/local/lib/R/site-library

# optionally, install example data
COPY temp/exampledata /exampledata/
RUN chown -R rstudio:rstudio /exampledata/*

# our standard mount point: shared directory between host and container where we can store data
RUN mkdir -m 777 /data

# change default working directory for RStudio server to /data
RUN echo "session-default-working-dir=/data" >> /etc/rstudio/rsession.conf
RUN echo "session-default-new-project-dir=/data" >> /etc/rstudio/rsession.conf
